name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install python
        uses: actions/setup-python@v5.4.0
      - name: Install poetry
        uses: abatilo/actions-poetry@v3.0.2
      - name: Setup a local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - name: Use caching for virtual environment
        uses: actions/cache@v4.2.0
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install project dependencies
        run: poetry install
      - name: Black format
        run: poetry run black --check .

  nix-fmt:
    name: nix format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Enable cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Nix format
        run: |
          nix develop --build --profile ci .#
          nix develop ./ci -c nixfmt --check .

  pytest:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install python
        uses: actions/setup-python@v5.4.0
      - name: Install poetry
        uses: abatilo/actions-poetry@v3.0.2
      - name: Setup a local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - name: Use caching for virtual environment
        uses: actions/cache@v4.2.0
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install project dependencies
        run: poetry install
      - name: pytest
        run: poetry run pytest
