name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install python
        uses: actions/setup-python@v5.6.0
      - name: Install uv
        uses: astral-sh/setup-uv@v6.3.1
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Ruff format
        run: uv run ruff check

  nix-fmt:
    name: nix format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Nix format
        run: nix-shell -p nixfmt-tree --run "treefmt --ci"

  pytest:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install python
        uses: actions/setup-python@v5.6.0
      - name: Install uv
        uses: astral-sh/setup-uv@v6.3.1
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: pytest
        run: uv run pytest
